apiVersion: v1
kind: Service
metadata:
  name: todo-list
spec:
  type: NodePort
  selector:
    app: todo-list
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      nodePort: 31000
